apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/standards: NIST SP 800-53
  name: metrics-forwarder-config
  namespace: openshift-acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
            name: metrics-forwarder-config
        spec:
            remediationAction: enforce
            evaluationInterval:
                compliant: 2h
                noncompliant: 45s
            object-templates:
                - complianceType: musthave
                  objectDefinition:
                    apiVersion: v1
                    kind: ConfigMap
                    metadata:
                      name: cluster-monitoring-config
                      namespace: openshift-monitoring
                    data:
                      config.yaml: |
                        enableUserWorkload: true
                        prometheusK8s:
                        # If the location of this config changes,
                        # make sure to adjust https://github.com/openshift/ops-sop/blob/master/v4/howto/observability/o11m_mst_killswitch.md
                        # so that killswitch instructions point to the right file!
                          externalLabels:
                            source: "dataplane-metrics"
                          replicas: 2
                          remoteWrite:
                            - url: https://metrics-forwarder.apps.{{ ( split "." (lookup "route.openshift.io/v1" "Route" "openshift-monitoring" "prometheus-k8s").spec.host )._2 }}.hypershift.local
                              remoteTimeout: 30s
                              writeRelabelConfigs:
                              - sourceLabels: [__name__]
                                action: keep
                              queueConfig:
                                capacity: 2500
                                maxShards: 1000
                                minShards: 1
                                maxSamplesPerSend: 500
                                batchSendDeadline: 60s
                                minBackoff: 30ms
                                maxBackoff: 5s
                              tlsConfig:
                                insecureSkipVerify: true
                          nodeSelector:
                            node-role.kubernetes.io/worker: ""
                          tolerations:
                            - effect: NoSchedule
                              key: node-role.kubernetes.io/worker
                              operator: Exists
                          retention: 11d
                          retentionSize: 90GB
                          volumeClaimTemplate:
                            metadata:
                              name: prometheus-data
                            spec:
                              resources:
                                requests:
                                  storage: 100Gi
                        alertmanagerMain:
                          nodeSelector:
                            node-role.kubernetes.io/worker: ""
                          tolerations:
                            - effect: NoSchedule
                              key: node-role.kubernetes.io/worker
                              operator: Exists
                          volumeClaimTemplate:
                            metadata:
                              name: alertmanager-data
                            spec:
                              resources:
                                requests:
                                  storage: 10Gi
                        telemeterClient:
                          nodeSelector:
                            node-role.kubernetes.io/worker: ""
                          tolerations:
                            - effect: NoSchedule
                              key: node-role.kubernetes.io/worker
                              operator: Exists
                          telemeterServerURL: https://infogw.api.stage.openshift.com
                        prometheusOperator:
                          nodeSelector:
                            node-role.kubernetes.io/worker: ""
                          tolerations:
                            - effect: NoSchedule
                              key: node-role.kubernetes.io/worker
                              operator: Exists
                        grafana:
                          nodeSelector:
                            node-role.kubernetes.io/worker: ""
                          tolerations:
                            - effect: NoSchedule
                              key: node-role.kubernetes.io/worker
                              operator: Exists
                        k8sPrometheusAdapter:
                          nodeSelector:
                            node-role.kubernetes.io/worker: ""
                          tolerations:
                            - effect: NoSchedule
                              key: node-role.kubernetes.io/worker
                              operator: Exists
                        kubeStateMetrics:
                          nodeSelector:
                            node-role.kubernetes.io/worker: ""
                          tolerations:
                            - effect: NoSchedule
                              key: node-role.kubernetes.io/worker
                              operator: Exists
                        openshiftStateMetrics:
                          nodeSelector:
                            node-role.kubernetes.io/worker: ""
                          tolerations:
                            - effect: NoSchedule
                              key: node-role.kubernetes.io/worker
                              operator: Exists
                        thanosQuerier:
                          nodeSelector:
                            node-role.kubernetes.io/worker: ""
                          tolerations:
                            - effect: NoSchedule
                              key: node-role.kubernetes.io/worker
                              operator: Exists
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: metrics-forwarder-rule
  namespace: openshift-acm-policies
spec:
  clusterSelector:
    matchExpressions:
    - key: hypershift.open-cluster-management.io/hosted-cluster
      operator: In
      values:
      - 'true'
    - key: name
      operator: In
      values:
      - '21smh37kqriosut45c6c5taugv7ovvq5'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: metrics-forwarder-placementbinding
  namespace: openshift-acm-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: metrics-forwarder-rule
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: metrics-forwarder-config
