apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: metrics-forwarder
spec:
  scopes:
    - Namespaced
  phases:
    - name: rbac
    - name: certman
    - name: config
    - name: deploy
    - name: expose
  availabilityProbes:
    - selector:
        kind:
          group: v1
          kind: ConfigMap
      probes:
      - condition:
        type: Available
        status: "True"
    - selector:
        kind:
          group: apps/v1
          kind: Deployment
      probes:
      - condition:
          type: Available
          status: "True"
      - fieldsEqual:
          fieldA: .status.updatedReplicas
          fieldB: .status.replicas
        